### ISSUE TITLE
New design for dashboard

### ISSUE THREAD

**Issue by EwelinaLasowy** [blumilksoftware/toby#152]
We should think again about the dashboard. At this moment dashboard for employee with vacation limit looks like this:
![image](https://user-images.githubusercontent.com/56546832/171134626-790dc382-b22d-4a80-abea-0bf8a1925a65.png)
 
But for users with no vacation limits it looks little worse:

![image](https://user-images.githubusercontent.com/56546832/171135590-efd1c238-70e5-4633-be50-2edd1d3c6cad.png)

But we can improve this view. For example we can make a calendar week view with a switch to month view and calendars should have a button that redirects to create a request page with a filled date. Below it can be the list of vacation requests. On the right side chart with vacation limits may be placed and list on today absences and holidays. And for users with no vacation limit we can hide the chart and show some statistics, for example how many days of absences they have or so.

Example of month view calendar [link](https://tailwindui.com/components/application-ui/data-display/calendars#component-c29139529079ea762f118812bbeaeb9e).

This is only my proposition. I’m open to suggestions.

**Comment by jsawo** [comment]
It would be nice if the absences tile
![image](https://user-images.githubusercontent.com/1294706/171829123-00c9d7ac-253b-43ee-8b87-722d6cf62ad1.png)

specified that there are no absences today instead of saying that there is no data - which suggests that there actually might be some absences, we just have no data on them.

**Comment by kamilniemczycki** [comment]
@jsawo, as of PR #120, the widget is invisible if there are no results for absences on a given day.

**Comment by jsawo** [comment]
> as of PR https://github.com/blumilksoftware/toby/issues/120, the widget is invisible if there are no results for absences on a given day.

yeah, I know - I'm just not convinced that it's actually a good way of handling this
