### ISSUE TITLE
Move from Heroku

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/toby#218]
With [these changes](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq) we won't be able to use Heroku for free as we are doing right now. We should move to our VPS, but it will require some changes, including:

- [ ] refactoring deploy workflow: https://github.com/blumilksoftware/toby/blob/main/.github/workflows/deploy.yml
- [ ] refactoring deploy informations (implemented in #179)
- [ ] removing Heroku artifacts (Procfile, etc.)
- [ ] and probably more?

The critical deadline is November 28, 2022, as Heroku will delete all free dynos this day. We should finish this task at least at begining of November.

**Comment by mtracz** [comment]
Actually we have configured VPS, with Docker, Traefik proxy and Portainer Business Edition. Also we have working domain names for toby, toby beta and other needed stuff.
These solutions will be helpful regarding to deploy project as containers.

I will prepare proposal migration document with the details to discuss.

The idea is to use Github Actions to deploy new releases to the VPS server and run up containers from specified docker-compose file.

**Comment by mtracz** [comment]
Status update about migration:

**Plan to move from Heroku to VPS:**
beta:
1. Create backup of Postgresql database from beta (@Baakoma will assist)
2. Deploy prepared project (branch # 218-vps-beta-setup) **manually** (deploy via Portainer or use GIT) It is the fastest way to check if everything is ok. Then we can focus on CI & CD flow.
3. Test if everything is working for beta environment

After these steps we can migrate production environment.
1. Backup live database on Heroku (@krzysztofrewak should be able to do it)
2. Provide environment variables from prod. (@krzysztofrewak should be able to do it)
3. Turn Toby live app on heroku to maintanance mode, to prevent add new data to the database.
4. Deploy prepared project (branch # 218-vps-live-setup) **manually**
5. Test if everything is ok.
---
Migration will be done after these steps.

**Steps to do after migration:**
- CI & CD via Github Actions
- Application footer (app version details) https://github.com/blumilksoftware/toby/issues/172
---

**Things to discuss before migration:**
1. Database instance (I prefer to use Postgresql as container, cause VPS service provider may be to expensive (240 PLN/month) [link](https://www.ovhcloud.com/pl/public-cloud/prices/#7261)
2. Database backup (I prefer to use [Duplicati](https://www.duplicati.com/) to do backups, its free, open-source and have a lot of [storage providers](https://duplicati.readthedocs.io/en/latest/05-storage-providers/). Another way is create commands to do backup and upload)

**Comment by mtracz** [comment]
Today we migrated data from Heroku to our VPS.
[VPS beta setup PR](https://github.com/blumilksoftware/toby/pull/250)
[VPS prod setup PR](https://github.com/blumilksoftware/toby/pull/251)

---
Steps to do in order of priority:
1. prepare backups for Postgres (backup and restore). https://github.com/blumilksoftware/toby/issues/252
2. CI & CD via Github Actions https://github.com/blumilksoftware/toby/issues/115
3. Application footer (app version details) https://github.com/blumilksoftware/toby/issues/172
