### ISSUE TITLE
Change notification in “Aktualne benefity”

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/toby#234]
For now in “Aktualne benefity” if the user is filling data and everything is okay he sees this notification:

![image](https://user-images.githubusercontent.com/56546832/191910027-e319c059-766a-453b-9d87-ef8471e105f2.png)

But if he makes some mistake, he sees error in this way:
![image](https://user-images.githubusercontent.com/56546832/191910133-c123ae58-7194-4835-ac1e-d4cda0dc79d7.png)

But in this case he should see notification albo at the top. Why? Because data is saving in real time and it's disturbing to see the notification all time at the bottom.

**Comment by kamilpiech97** [comment]
I did not see that error in code :eyes: @EwelinaSkrzypacz

**Comment by kamilpiech97** [comment]
After dicussion with @EwelinaSkrzypacz, we can close that issue
