### ISSUE TITLE
Database backup and restore

### ISSUE THREAD

**Issue by mtracz** [blumilksoftware/toby#252]
We should implement backup and restore functionality for Postgres database.
Backup action should be scheduled (probably as job or command via scheduler).

Probably we will utilise [Duplicati](https://www.duplicati.com/) app as a container, to upload backup files in some data store provider, like Google drive, S3, etc..
But if you have other idea, fell free to share with details in this issue.

Backup:
- automatically
- manually

Restore:
- manually

**Comment by mtracz** [comment]
@krzysztofrewak 
Would you like to have notifications regarding to success or fail automatically backup? If so, on which channel, email, Slack?

**Comment by krzysztofrewak** [comment]
> @krzysztofrewak Would you like to have notifications regarding to success or fail automatically backup? If so, on which channel, email, Slack?

Email would be fine, I think.
