### ISSUE TITLE
Refresh button/update indicator

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/toby#270]
I would like to have an indicator that could tell me that displayed data are outdated. I can see two way to handle this:
* easier: save timestamp of visit somewhere in the frontend and display "Refresh me!" button in navigation when for example day changes
* more complex: create an endpoint with hash/date of last database change and ping it every x minutes (and then display button "Referesh me!"

Something similar is implemented in Github pull requests. When you are on Files changed tab (eg. https://github.com/blumilksoftware/toby/pull/269/files) and someone pushes some new changes to the branch in question, "Refresh me!" button appears almost automatically.

Proposed frontend solution:

![image](https://user-images.githubusercontent.com/10898728/205869915-b964282c-89e1-4ba5-8680-74a63fe16c50.png)

**Comment by EwelinaSkrzypacz** [comment]
But we have information that year is outdated ("Wróć do obecnego roku")

![image](https://github.com/blumilksoftware/toby/assets/56546832/314d9089-ca45-46d0-adc0-2406716d8c84)

**Comment by krzysztofrewak** [comment]
That's not what I'm talking about. I have Toby tab pinned to the browser. Very often I have a situation where I'm checking something on dashboard main screen and all data are outdated, because I haven't refreshed the page.
