### ISSUE TITLE
Upgrade to Laravel 10

### ISSUE THREAD

**Issue by EwelinaLasowy** [blumilksoftware/toby#289]
Reminder to upgrade project to Laravel 10. But it's some blockers here, like rackbeat/laravel-ui-avatars package that is not supporting Laravel 10 yet.

**Comment by krzysztofrewak** [comment]
Status: https://github.com/Rackbeat/laravel-ui-avatars/pull/13

**Comment by krzysztofrewak** [comment]
i would like to bump PHP to 8.2 and our Codestyle to 2.0.
