### ISSUE TITLE
Calendar navigation behaviour

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/toby#377]
Calendar navigation is a bit overengineered, I thnk.

Today we have December 12, 2023. If I would like to see calendar for January 2024, I need to:
* change year in navigation bar
* click "previous month"... 11 times
* and this would result with new and final url: `/calendar/january`

Maybe `/calendar/2024/01` would be better? Maybe We should have "next month" button not only in scope of year? Or maybe we could do at least some dropdown with month names? I am leaving this for discussion.

**Comment by Baakoma** [comment]
Implemented in #495
