### ISSUE TITLE
Add overtime

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/toby#444]
So, employees sometimes have overtime and such information is important for HR as it affects payouts. 
As an employee I want to create some kind of "overtime request" - in the form it should be information like when, what time it starts, what time it ends, non editable field with number of hours. It will be useful to see list of all my overtimes.
As a technical approver/admin I want to approve/refuse overtime. When I accept it, the administrative approve can see this. Also I want to accept/refuse on Slack. Also I want to see list of all overtimes.
As a administrative approver/admin I want to see accepted overtimes - like in .csv file? Or maybe we can merge somehow file with working hours report?  Or just make list with all overtimes and on the top on the page will be button to download accepted overtimes?

**Comment by kamilpiech97** [comment]
Should be clarified with Kamila:
- how should be generated reports of overtime (maybe like CSV with working hours per moth for all employes)
- should overtime have field with information about how overtime should be settled
- overtime hours paid should be recognized in some way

**Comment by kamilpiech97** [comment]
> Should be clarified with Kamila:
> 
> 1. how should be generated reports of overtime (maybe like CSV with working hours per moth for all employes) - tak jak w godiznach
> 2. should overtime have field with information about how overtime should be settled - ma być opcja kasa albo czas
> 3. overtime hours paid should be recognized in some way - można to jakoś statusować
> 4. edge cases like limit of overtime or what about overtime on turn of the years/months - nie utrudniamy
> 5. precision of overtime hours/minutes - co do godzin

After discuss with Kamil, I have answers:
1. Like in CSV with working hours per moth for all employes
2. Overtime should have option to choose - money or overtime to be collected from working time
3. We should add status for overtime settled
4. It should be done in a simple way without hundreds of cases to handle
5. Hours precision.
