### ISSUE TITLE
User profile table cleaning

### ISSUE THREAD

**Issue by kamilpiech97** [blumilksoftware/toby#452]
We should after deployment that [PR](https://github.com/blumilksoftware/toby/pull/451) clean user profile, I mean about fields in `profiles` table in database.
We should remove these fields:
- nextMedicalExamDate,
- lastMedicalExamDate,
- nextOhsTrainingDate,
- lastOhsTrainingDate.

**Comment by EwelinaSkrzypacz** [comment]
And also things related to employment form and date

**Comment by kamilpiech97** [comment]
Closed with #472.
