### ISSUE TITLE
Add information about which user is viewed on user details view

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/toby#486]
As user with permissions to user, when I go to "Użytkownicy" -> choose person -> "Szczegóły" I don't see what user this page is about. We can add information like here:

![image](https://github.com/user-attachments/assets/7308e6e0-3420-44f0-ba3e-a44ab53bc6ca)

**Comment by krzysztofrewak** [comment]
Duplicate of https://github.com/blumilksoftware/toby/issues/484?

**Comment by EwelinaSkrzypacz** [comment]
I think so
